In [1]:
from __future__ import print_function, division
from builtins import range, input

In [4]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, GRU
import numpy as np
import matplotlib.pyplot as plt

In [5]:
T = 8
D = 2
M = 3

In [6]:
X = np.random.randn(1, T, D)

In [7]:
def lstm1():
  input_ = Input(shape=(T, D))
  rnn = LSTM(M, return_state=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h, c = model.predict(X)
  print("o:", o)
  print("h:", h)
  print("c:", c)

In [8]:
def lstm2():
  input_ = Input(shape=(T, D))
  rnn = LSTM(M, return_state=True, return_sequences=True)
  # rnn = GRU(M, return_state=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h, c = model.predict(X)
  print("o:", o)
  print("h:", h)
  print("c:", c)

In [9]:
def gru1():
  input_ = Input(shape=(T, D))
  rnn = GRU(M, return_state=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h = model.predict(X)
  print("o:", o)
  print("h:", h)

In [10]:
def gru2():
  input_ = Input(shape=(T, D))
  rnn = GRU(M, return_state=True, return_sequences=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h = model.predict(X)
  print("o:", o)
  print("h:", h)

In [11]:
print("lstm1:")
lstm1()
print("lstm2:")
lstm2()
print("gru1:")
gru1()
print("gru2:")
gru2()

lstm1:
Metal device set to: Apple M1 Max

systemMemory: 64.00 GB
maxCacheSize: 24.00 GB



2022-03-27 21:20:59.764560: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-03-27 21:20:59.764671: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2022-03-27 21:21:00.013476: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-03-27 21:21:00.134828: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-03-27 21:21:00.196458: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


o: [[-0.01730855 -0.00057424 -0.08383728]]
h: [[-0.01730855 -0.00057424 -0.08383728]]
c: [[-0.04033358 -0.00105233 -0.15887207]]
lstm2:


2022-03-27 21:21:01.303779: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-03-27 21:21:01.338403: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


o: [[[-0.01351425 -0.00506733 -0.00709051]
  [ 0.15516324 -0.07690861  0.03553857]
  [ 0.11953814 -0.11037374  0.03495307]
  [ 0.18413112 -0.13413958  0.0503289 ]
  [ 0.06568261 -0.17850454  0.00124175]
  [ 0.07041039 -0.11754791 -0.01166848]
  [ 0.03864627 -0.03862643 -0.04289687]
  [-0.00520942 -0.00696062 -0.06924865]]]
h: [[-0.00520942 -0.00696062 -0.06924865]]
c: [[-0.0126809  -0.0127945  -0.13105206]]
gru1:


2022-03-27 21:21:01.672968: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-03-27 21:21:01.701612: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


o: [[ 0.372872    0.45077613 -0.23971158]]
h: [[ 0.372872    0.45077613 -0.23971158]]
gru2:
o: [[[ 0.1795511   0.16171902 -0.10687837]
  [-0.17159446 -0.10205083  0.10894652]
  [ 0.07751743  0.10065709 -0.03057584]
  [ 0.02764704  0.05535852 -0.05139613]
  [ 0.5498217   0.49494976 -0.46695158]
  [ 0.4200687   0.3354839  -0.4303531 ]
  [ 0.15212414  0.06758367 -0.2839322 ]
  [ 0.32954592  0.21946062 -0.2996341 ]]]
h: [[ 0.32954592  0.21946062 -0.2996341 ]]


2022-03-27 21:21:02.153555: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-03-27 21:21:02.184183: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
